### ISSUE TITLE
Dataset for india statewise

### ISSUE THREAD

**Issue by Chiragg01** [ammishra08/COVID-19#1]
Sir, can you upload the data for India statewise as it there earlier or if you could guide as to where i can get it.

**Comment by ammishra08** [comment]
Please Follow :
https://github.com/ammishra08/COVID-19/tree/master/covid_19_datasets/covid19_india

**Comment by Chiragg01** [comment]
Thank You so much helped a lot 
I don't know but the other data sets were not letting me sort the values
could you help with you email id i never got it.

**Comment by Chiragg01** [comment]
Lastly, how to collect this data and if i want this state wise data along with the dates 
like we have the global data date wise is it possible.
